version: 2

models:
  - name: stg_customers
    description: "Cleaned and standardized customer data"
    columns:
      - name: customer_id
        description: "Unique identifier for each customer"
        tests:
          - unique
          - not_null
      - name: email
        description: "Customer email address"
        tests:
          - unique
          - not_null
      - name: registration_date
        description: "Date when customer registered"
        tests:
          - not_null

  - name: stg_products
    description: "Cleaned and standardized product catalog data"
    columns:
      - name: product_id
        description: "Unique identifier for each product"
        tests:
          - unique
          - not_null
      - name: price
        description: "Product selling price"
        tests:
          - not_null
      - name: cost
        description: "Product cost"
        tests:
          - not_null
      - name: profit_margin
        description: "Calculated profit margin (price - cost)"
        tests:
          - not_null

  - name: stg_orders
    description: "Cleaned and standardized order data"
    columns:
      - name: order_id
        description: "Unique identifier for each order"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Foreign key to customers"
        tests:
          - not_null
      - name: order_date
        description: "Date when order was placed"
        tests:
          - not_null
      - name: status
        description: "Current order status"
        tests:
          - not_null
          - accepted_values:
              values: ['pending', 'processing', 'shipped', 'completed', 'cancelled', 'refunded']

  - name: stg_order_items
    description: "Cleaned and standardized order line items"
    columns:
      - name: order_item_id
        description: "Unique identifier for each order item"
        tests:
          - unique
          - not_null
      - name: order_id
        description: "Foreign key to orders"
        tests:
          - not_null
      - name: product_id
        description: "Foreign key to products"
        tests:
          - not_null
      - name: quantity
        description: "Quantity of product ordered"
        tests:
          - not_null
      - name: line_total_after_discount
        description: "Total line amount after discounts"
        tests:
          - not_null