version: 2

seeds:
  - name: raw_customers
    description: "Raw customer data from the CRM system"
    columns:
      - name: customer_id
        description: "Unique identifier for each customer"
        tests:
          - unique
          - not_null
      - name: email
        description: "Customer email address"
        tests:
          - unique
          - not_null
      - name: first_name
        tests:
          - not_null
      - name: last_name
        tests:
          - not_null
      - name: registration_date
        tests:
          - not_null

  - name: raw_products
    description: "Raw product catalog data"
    columns:
      - name: product_id
        description: "Unique identifier for each product"
        tests:
          - unique
          - not_null
      - name: product_name
        tests:
          - not_null
      - name: price
        tests:
          - not_null
      - name: cost
        tests:
          - not_null
      - name: sku
        description: "Stock keeping unit identifier"
        tests:
          - unique
          - not_null

  - name: raw_orders
    description: "Raw order transaction data"
    columns:
      - name: order_id
        description: "Unique identifier for each order"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Foreign key to customers table"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('raw_customers')
                field: customer_id
      - name: order_date
        tests:
          - not_null
      - name: status
        tests:
          - not_null
          - accepted_values:
              values: ['pending', 'processing', 'shipped', 'completed', 'cancelled', 'refunded']
      - name: total_amount
        tests:
          - not_null

  - name: raw_order_items
    description: "Raw order line items data"
    columns:
      - name: order_item_id
        description: "Unique identifier for each order item"
        tests:
          - unique
          - not_null
      - name: order_id
        description: "Foreign key to orders table"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('raw_orders')
                field: order_id
      - name: product_id
        description: "Foreign key to products table"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('raw_products')
                field: product_id
      - name: quantity
        tests:
          - not_null
      - name: unit_price
        tests:
          - not_null